### PR TITLE
Working on RFCs and closes #2.

### LINKED ISSUE #2: Either pebcak or missing shortcodes
Did you have an unchecked in version of the shortcode for 'icon' or 'notice'? Im not super familiar with hugo but googling didnt reveal if 'notice' or 'icon' were apart of the built in hugo shortcodes.

The error I got is:
```
bneil@bucket:~/src/go/src/github.com/gaia-pipeline/docs$ hugo server
Building sites … ERROR 2018/08/30 21:06:37 Unable to locate template for shortcode "notice" in page "_index.md"
ERROR 2018/08/30 21:06:37 Unable to locate template for shortcode "notice" in page "develop-pipelines/python.md"
ERROR 2018/08/30 21:06:37 Unable to locate template for shortcode "icon" in page "tutorials/kube-vault-deploy/create-pipeline.md"
ERROR 2018/08/30 21:06:37 Unable to locate template for shortcode "icon" in page "tutorials/kube-vault-deploy/run-tests-compile.md"
ERROR 2018/08/30 21:06:37 Unable to locate template for shortcode "icon" in page "tutorials/kube-vault-deploy/_index.md"
ERROR 2018/08/30 21:06:37 Unable to locate template for shortcode "icon" in page "tutorials/kube-vault-deploy/setup.md"
ERROR 2018/08/30 21:06:37 Unable to locate template for shortcode "notice" in page "develop-pipelines/java.md"
ERROR 2018/08/30 21:06:37 Unable to locate template for shortcode "notice" in page "develop-pipelines/golang.md"
ERROR 2018/08/30 21:06:37 Unable to locate template for shortcode "icon" in page "getting-started/track-pipeline-run.md"
ERROR 2018/08/30 21:06:37 Unable to locate template for shortcode "icon" in page "getting-started/final-words.md"
Total in 73 ms
Error: Error building site: logged 10 error(s)
```

Do you want me to toss in those shortcodes or am I missing something?

### PR DESCRIPTION
**Pull request by Skarlso**
@michelvocks WIP. Added RFCs to the list and added a README of how to build locally to document the submodules.

I want the RFCS to be part of Gaia if you don't mind. :)

### CODE REVIEW

**Comment by michelvocks** [comment]
@Skarlso wonderful. Love it! ❤️ 
Let me know when it's ready for review.

**Comment by Skarlso** [comment]
Okay. Just gonna improver the readme and the proper _index for the rfc. 🙂

**Comment by Skarlso** [comment]
@michelvocks Updated readme and the index file. Tell me what you think. :)

**Comment by michelvocks** [comment]
LGTM 🤗

**Pull request merged**
